language: php

php:
  - "5.4"
  - "5.5"
  - "5.6"
  - "7.0"

env:
  matrix:
    - CONTAO_VERSION=~3.4.4

sudo: false

install:
  - composer require contao/core $CONTAO_VERSION --prefer-dist --dev
  - composer install --prefer-dist --dev

script: ant -keep-going

# Hack to make things work again - we can not use a shallow repository.
git:
  depth: 2147483647